### ISSUE TITLE
Support \Traversable (e.g. generator) for Writer::addRows()

### ISSUE THREAD

**Issue by mbrodala** [nimmneun/onesheet#42]
It would be nice if `Writer::addRows()` could accept a `\Traversable` (e.g. a generator) instead of only an array. Right now one either has to use `iterator_to_array()` or `Writer::addRow()` and `foreach`.

**Comment by nimmneun** [comment]
The only option would probably be to not typehint, otherwise plain arrays would no longer work. The validation might have to be dropped as well, since it requires a \Countable implementation. So we'd end up with this I guess =)

```php
    public function addRows($rows, Style $style = null)
    {
        foreach ($rows as $row) {
            $this->addRow($row, $style);
        }
    }
```

I chose plain array b/c pretty much all collection implementations either allow a typecast to array or implement a toArray() method.

But feel free to create a pull request, if you have a different/specific solution in mind =)

**Comment by mbrodala** [comment]
Until we have union types in PHP it basically boils down to what you wrote. I'd add a runtime type check just to be sure since the default `Invalid argument supplied for foreach` warning of PHP is not useful.
